FROM node:22-slim
WORKDIR /app
COPY landing/package*.json ./landing/
WORKDIR /app/landing
RUN npm install
WORKDIR /app
COPY landing ./landing
WORKDIR /app/landing
EXPOSE 4321
CMD ["sh", "-c", "npm install && npm run dev -- --host"]
