FROM node:22-slim
WORKDIR /app
COPY adminClient/package*.json ./adminClient/
WORKDIR /app/adminClient
RUN npm install
WORKDIR /app
COPY adminClient ./adminClient
WORKDIR /app/adminClient
EXPOSE 5173
CMD ["sh", "-c", "npm install && npm run dev"]
