FROM node:22-slim
WORKDIR /app
COPY client/package*.json ./client/
WORKDIR /app/client
RUN npm install
WORKDIR /app
COPY client ./client
WORKDIR /app/client
EXPOSE 8081
CMD ["sh", "-c", "npm install && npx expo start --web --port 8081"]
