services:
  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
      target: ${NODE_ENV:-development}
    container_name: api
    ports:
      - "${API_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PGHOST=db
      - API_PORT=${API_PORT}
    volumes:
      - ./api:/app         # monta tu código local (TS) en dev
      - /app/node_modules  # evita sobreescribir node_modules del contenedor
    depends_on:
      - db
volumes:
  postgres-data: