services:
  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: ../
      dockerfile: ./api.Dockerfile
      target: ${NODE_ENV:-development}
    container_name: api
    ports:
      - "${API_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PGHOST=db
      - API_PORT=${API_PORT}
    volumes:
      - ./api/src:/app/src
      - /app/node_modules
      - ./uploads:/uploads
    depends_on:
      - db
volumes:
  postgres-data: