/**
 * Las comunidades del dataset demo.
 *
 * `DEMO_COMMUNITY_BLUEPRINT` es la que se muestra en producción al entrar en modo demo:
 * una sola comunidad, con contenido suficiente para recorrer la app entera sin huecos. Las otras
 * dos existen solo en desarrollo y están para lo que una sola comunidad no puede probar —
 * aislamiento entre inquilinos, resolución de comunidad por dominio de email y temas distintos.
 */
import type { CommunityBlueprint } from "./buildCommunity";

/**
 * Paleta por defecto de la app. Duplica `DEFAULT_COLORS` de `client/config.ts` a propósito: este
 * paquete no puede importar del cliente (lo consume también el servidor). Si se toca una, tocar
 * la otra — y `client/global.css`, que ya arrastra la misma duplicación.
 */
const DEFAULT_PALETTE: CommunityThemeColors = {
  primary: "#FF5900",
  secondary: "#4C9F38",
  tertiary: "#009E7C",
  mainText: "#424242",
  secondaryText: "#9E9E9E",
  credits: "#8436D1",
  creditsLight: "#8F4CD1",
  stroke: "#E4E4E4",
  background: "#F0F0F0",
  alert: "#FF3B30",
};

export const DEMO_COMMUNITY_BLUEPRINT: CommunityBlueprint = {
  slug: "demo",
  name: "Comunidad Demo",
  emailDomains: ["demo.edu"],
  colors: DEFAULT_PALETTE,
  showcase: "ana",
  completedLoops: 320,
  admin: { email: "admin@demo.edu", fullName: "Admin Comunidad Demo" },
  // Una solicitud pendiente para que la pantalla de borrados del panel no arranque vacía.
  deletionRequests: [{ member: "julian", agoHours: 30 }],
  schools: ["Escuela Primaria Demo", "Escuela Secundaria Demo", "Instituto Técnico Demo"],
  members: [
    {
      key: "ana",
      firstName: "Ana",
      lastName: "Gómez",
      phone: "11 2345-6789",
      credits: 1500,
      schools: ["Escuela Primaria Demo", "Escuela Secundaria Demo"],
      avatar: true,
    },
    {
      key: "carlos",
      firstName: "Carlos",
      lastName: "Fernández",
      credits: 900,
      schools: ["Escuela Secundaria Demo"],
    },
    {
      key: "lucia",
      firstName: "Lucía",
      lastName: "Martínez",
      credits: 1200,
      schools: ["Instituto Técnico Demo"],
    },
    {
      key: "martin",
      firstName: "Martín",
      lastName: "Rodríguez",
      credits: 700,
      schools: ["Escuela Secundaria Demo"],
      avatar: true,
    },
    {
      key: "sofia",
      firstName: "Sofía",
      lastName: "López",
      credits: 2000,
      schools: ["Escuela Primaria Demo"],
    },
    {
      key: "julian",
      firstName: "Julián",
      lastName: "Torres",
      credits: 450,
      schools: ["Instituto Técnico Demo"],
    },
  ],
  listings: [
    {
      key: "buzo-gris",
      seller: "ana",
      title: "Buzo escolar gris talle 12",
      description:
        "Buzo de uniforme gris, talle 12, con logo bordado. Casi sin uso, se usó un cuatrimestre.",
      category: "Buzos y camperas",
      price: 6000,
      listingStatus: "published",
      productStatus: "like_new",
      agoHours: 72,
      images: ["loop-demo-buzo-1", "loop-demo-buzo-2"],
    },
    {
      key: "cartuchera-tela",
      seller: "ana",
      buyer: "carlos",
      title: "Cartuchera de tela con cierre",
      description:
        "Cartuchera de tela estampada con cierre en buen estado. Perfecta para lápices y marcadores.",
      category: "Cartucheras",
      price: 1500,
      offeredCredits: 1200,
      listingStatus: "offered",
      productStatus: "good",
      agoHours: 120,
      images: ["loop-demo-cartuchera"],
    },
    {
      key: "set-geometria",
      seller: "carlos",
      title: "Set de geometría completo",
      description: "Regla, escuadra, transportador y compás en estuche original. Se usó dos años.",
      category: "Reglas, escuadras y compases",
      price: 800,
      listingStatus: "published",
      productStatus: "good",
      agoHours: 48,
      images: ["loop-demo-geometria"],
    },
    {
      key: "cuadernos-a4",
      seller: "carlos",
      title: "Cuadernos A4 tapa dura (x3)",
      description: "Tres cuadernos A4 tapa dura, rayados, sin usar. Ideales para secundaria.",
      category: "Cuadernos",
      price: 2000,
      listingStatus: "published",
      productStatus: "like_new",
      agoHours: 96,
      images: ["loop-demo-cuadernos"],
    },
    {
      key: "mochila-azul",
      seller: "lucia",
      title: "Mochila escolar azul",
      description:
        "Mochila azul con dos compartimentos y soporte acolchado. Tiene un pequeño desgaste en la base.",
      category: "Mochilas",
      price: 8000,
      listingStatus: "published",
      productStatus: "fair",
      agoHours: 144,
      images: ["loop-demo-mochila-1", "loop-demo-mochila-2"],
    },
    {
      key: "botella-termica",
      seller: "lucia",
      title: "Botella de agua térmica",
      description:
        "Botella térmica de acero inoxidable, 500 ml. Mantiene el agua fría todo el día.",
      category: "Botellas de agua y loncheras",
      price: 1200,
      listingStatus: "published",
      productStatus: "like_new",
      agoHours: 24,
      images: ["loop-demo-botella"],
    },
    {
      key: "acuarelas",
      seller: "martin",
      title: "Acuarelas x12 colores",
      description: "Caja de acuarelas de 12 colores, usadas un par de veces. Incluye pincel.",
      category: "Material artístico",
      price: 1800,
      listingStatus: "published",
      productStatus: "good",
      agoHours: 168,
      images: ["loop-demo-acuarelas"],
    },
    {
      key: "zapatos-uniforme",
      seller: "martin",
      buyer: "ana",
      title: "Zapatos de uniforme talle 33",
      description:
        "Zapatos negros de vestir para uniforme, talle 33. En buen estado, suela sin desgaste.",
      category: "Zapatos escolares",
      price: 9000,
      offeredCredits: 7500,
      listingStatus: "accepted",
      productStatus: "fair",
      agoHours: 216,
      images: ["loop-demo-zapatos"],
    },
    {
      key: "marcadores",
      seller: "julian",
      title: "Marcadores de colores (estuche x10)",
      description:
        "Estuche de 10 marcadores escolares, casi todos con tinta. Se cambiaron algunos por nuevos.",
      category: "Marcadores y resaltadores",
      price: 1000,
      listingStatus: "published",
      productStatus: "good",
      agoHours: 288,
      images: ["loop-demo-marcadores"],
    },
    {
      key: "carpeta-a4",
      seller: "sofia",
      title: "Carpeta A4 con repuestos",
      description: "Carpeta A4 lisa con repuestos de hojas rayadas y cuadriculadas. Como nueva.",
      category: "Carpetas y repuestos de hojas",
      price: 2500,
      listingStatus: "published",
      productStatus: "like_new",
      agoHours: 192,
      images: ["loop-demo-carpeta"],
    },
    {
      key: "lapices-colores",
      seller: "lucia",
      buyer: "ana",
      title: "Lápices de colores x24",
      description: "Caja de 24 lápices de colores, algunos levemente gastados. Todos funcionan.",
      category: "Lápices y lapiceras",
      price: 1400,
      offeredCredits: 1100,
      listingStatus: "received",
      productStatus: "good",
      agoHours: 240,
      images: ["loop-demo-lapices"],
    },
  ],
  missions: [
    {
      member: "ana",
      mission: "first_listing",
      completed: true,
      completedAgoHours: 96,
      progress: { total: 1, current: 1 },
    },
    {
      member: "ana",
      mission: "complete_profile",
      completed: true,
      completedAgoHours: 144,
      progress: { total: 1, current: 1 },
    },
    {
      member: "ana",
      mission: "three_loops",
      completed: false,
      progress: { total: 3, current: 1 },
    },
    { member: "ana", mission: "donate", completed: false, progress: { total: 1, current: 0 } },
  ],
  messages: [
    {
      key: "sofia-ana-1",
      from: "sofia",
      to: "ana",
      text: "¡Hola Ana! ¿El buzo gris todavía está disponible?",
      listing: "buzo-gris",
      agoHours: 50,
      isRead: true,
    },
    {
      key: "ana-sofia-1",
      from: "ana",
      to: "sofia",
      text: "¡Hola Sofía! Sí, todavía está disponible.",
      agoHours: 49,
      isRead: true,
    },
    {
      key: "sofia-ana-2",
      from: "sofia",
      to: "ana",
      text: "Genial, ¿lo puedo pasar a buscar el viernes?",
      agoHours: 5,
      isRead: false,
    },
    {
      key: "ana-martin-1",
      from: "ana",
      to: "martin",
      text: "Hola Martín, ¿los cuadernos son de tapa dura?",
      listing: "cuadernos-a4",
      agoHours: 76,
      isRead: true,
    },
    {
      key: "martin-ana-1",
      from: "martin",
      to: "ana",
      text: "Sí, los tres son tapa dura y están sin usar.",
      agoHours: 75,
      isRead: true,
    },
  ],
  notifications: [
    {
      key: "ana-mission-first",
      member: "ana",
      agoHours: 98,
      readAgoHours: 96,
      payload: { kind: "mission", mission: "first_listing" },
    },
    {
      key: "ana-loop-offer",
      member: "ana",
      agoHours: 54,
      payload: {
        kind: "loop",
        listing: "cartuchera-tela",
        buyer: "carlos",
        toListingStatus: "offered",
        toOfferedCredits: 1200,
        type: "new_offer",
      },
    },
    {
      key: "ana-donation",
      member: "ana",
      agoHours: 27,
      payload: { kind: "donation", donor: "julian", amount: 100 },
    },
  ],
  wishes: [
    {
      member: "ana",
      category: "Mochilas",
      comment: "Busco una mochila de tela para primer grado.",
    },
    { member: "ana", category: "Cuadernos" },
  ],
};

/** Segunda comunidad, solo para dev: paleta y dominio distintos, contenido acotado. */
const VERDE_BLUEPRINT: CommunityBlueprint = {
  slug: "colegio-verde",
  name: "Colegio Verde",
  emailDomains: ["colegioverde.edu.ar"],
  colors: {
    ...DEFAULT_PALETTE,
    primary: "#2E7D32",
    secondary: "#8BC34A",
    tertiary: "#00796B",
    credits: "#1B5E20",
    creditsLight: "#388E3C",
  },
  showcase: "valentina",
  completedLoops: 84,
  admin: { email: "admin@colegioverde.edu.ar", fullName: "Admin Colegio Verde" },
  schools: ["Colegio Verde Norte", "Colegio Verde Sur"],
  members: [
    {
      key: "valentina",
      firstName: "Valentina",
      lastName: "Pérez",
      phone: "11 4455-6677",
      credits: 1800,
      schools: ["Colegio Verde Norte"],
      avatar: true,
    },
    {
      key: "tomas",
      firstName: "Tomás",
      lastName: "Aguirre",
      credits: 600,
      schools: ["Colegio Verde Sur"],
    },
    {
      key: "camila",
      firstName: "Camila",
      lastName: "Ríos",
      credits: 1100,
      schools: ["Colegio Verde Norte", "Colegio Verde Sur"],
    },
  ],
  listings: [
    {
      key: "campera-verde",
      seller: "valentina",
      title: "Campera de egresados talle M",
      description: "Campera del colegio, talle M, usada una temporada. Cierre impecable.",
      category: "Buzos y camperas",
      price: 7000,
      listingStatus: "published",
      productStatus: "good",
      agoHours: 60,
      images: ["loop-verde-campera"],
    },
    {
      key: "mochila-verde",
      seller: "tomas",
      title: "Mochila con ruedas",
      description: "Mochila con ruedas y manija telescópica. Ideal para primaria.",
      category: "Mochilas",
      price: 9500,
      listingStatus: "published",
      productStatus: "fair",
      agoHours: 130,
      images: ["loop-verde-mochila"],
    },
    {
      key: "temperas-verde",
      seller: "camila",
      buyer: "valentina",
      title: "Témperas x6 y pinceles",
      description: "Set de témperas de 6 colores con tres pinceles. Casi sin usar.",
      category: "Material artístico",
      price: 1600,
      offeredCredits: 1400,
      listingStatus: "received",
      productStatus: "like_new",
      agoHours: 300,
      images: ["loop-verde-temperas"],
    },
  ],
  missions: [
    {
      member: "valentina",
      mission: "first_listing",
      completed: true,
      completedAgoHours: 58,
      progress: { total: 1, current: 1 },
    },
    {
      member: "valentina",
      mission: "three_loops",
      completed: false,
      progress: { total: 3, current: 1 },
    },
  ],
  messages: [
    {
      key: "tomas-valentina-1",
      from: "tomas",
      to: "valentina",
      text: "¿La campera tiene el escudo bordado o estampado?",
      listing: "campera-verde",
      agoHours: 30,
      isRead: false,
    },
  ],
  notifications: [
    {
      key: "valentina-mission-first",
      member: "valentina",
      agoHours: 58,
      readAgoHours: 57,
      payload: { kind: "mission", mission: "first_listing" },
    },
  ],
  wishes: [
    { member: "valentina", category: "Cuadernos", comment: "Cuadernos A4 rayados, los que sean." },
  ],
};

/** Tercera comunidad, solo para dev. Existe sobre todo para que el aislamiento se note. */
const AUSTRAL_BLUEPRINT: CommunityBlueprint = {
  slug: "instituto-austral",
  name: "Instituto Austral",
  emailDomains: ["austral.edu.uy"],
  colors: {
    ...DEFAULT_PALETTE,
    primary: "#1565C0",
    secondary: "#0288D1",
    tertiary: "#00838F",
    credits: "#283593",
    creditsLight: "#3949AB",
  },
  showcase: "bruno",
  completedLoops: 41,
  admin: { email: "admin@austral.edu.uy", fullName: "Admin Instituto Austral" },
  schools: ["Instituto Austral"],
  members: [
    {
      key: "bruno",
      firstName: "Bruno",
      lastName: "Silva",
      credits: 2200,
      schools: ["Instituto Austral"],
      avatar: true,
    },
    {
      key: "renata",
      firstName: "Renata",
      lastName: "Correa",
      credits: 350,
      schools: ["Instituto Austral"],
    },
  ],
  listings: [
    {
      key: "camisa-austral",
      seller: "bruno",
      title: "Camisas de uniforme talle 14 (x2)",
      description: "Dos camisas blancas de uniforme, talle 14. Sin manchas ni roturas.",
      category: "Camisas y remeras",
      price: 4000,
      listingStatus: "published",
      productStatus: "good",
      agoHours: 40,
      images: ["loop-austral-camisa"],
    },
    {
      key: "lonchera-austral",
      seller: "renata",
      buyer: "bruno",
      title: "Lonchera térmica con botella",
      description: "Lonchera térmica con botella de 500 ml incluida. Se usó medio año.",
      category: "Botellas de agua y loncheras",
      price: 2400,
      offeredCredits: 2000,
      listingStatus: "offered",
      productStatus: "like_new",
      agoHours: 90,
      images: ["loop-austral-lonchera"],
    },
  ],
  missions: [
    {
      member: "bruno",
      mission: "complete_profile",
      completed: true,
      completedAgoHours: 200,
      progress: { total: 1, current: 1 },
    },
  ],
  messages: [],
  notifications: [
    {
      key: "renata-loop-offer",
      member: "renata",
      agoHours: 20,
      payload: {
        kind: "loop",
        listing: "lonchera-austral",
        buyer: "bruno",
        toListingStatus: "offered",
        toOfferedCredits: 2000,
        type: "new_offer",
      },
    },
  ],
  wishes: [{ member: "renata", category: "Mochilas" }],
};

/** Solo la comunidad demo: es lo que se publica en producción. */
export const DEMO_BLUEPRINTS: CommunityBlueprint[] = [DEMO_COMMUNITY_BLUEPRINT];

/** Todo el dataset: la demo más las comunidades extra que solo tienen sentido en desarrollo. */
export const DEV_BLUEPRINTS: CommunityBlueprint[] = [
  DEMO_COMMUNITY_BLUEPRINT,
  VERDE_BLUEPRINT,
  AUSTRAL_BLUEPRINT,
];
